export const CarrelloActionTypes = {
    TOGGLE_ANTEPRIMA: 'TOGGLE_ANTEPRIMA',
    CHIUDI_CARRELLO: 'CHIUDI_CARRELLO',
    ADD_PRODOTTO: 'ADD_PRODOTTO',
    REMOVE_PRODOTTO: 'REMOVE_PRODOTTO',
    CANCELLA_ELEMENTO: 'CANCELLA_ELEMENTO',
    SVUOTA_CARRELLO: 'SVUOTA_ELEEMENTO',
    SVUOTA_CARRELLO_FE: 'SVUOTA_ELEEMENTO_FE',
    RETRIEVE_CARRELLO: 'RETRIEVE_CARRELLO'
};